In [1]:
import numpy as np
import pandas as pd

# 4 NumPy Basics: Arrays and Vectorized Computation

NumPY short for numerical python, good for numerical computing in python. ndarray, an efficient multidimentsional array good for flexible broadcasting capabilities. 

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 17.3 ms, sys: 14.8 ms, total: 32.1 ms
Wall time: 43.2 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 249 ms, sys: 75.2 ms, total: 324 ms
Wall time: 344 ms


NumPy based algorithms are generally 10 to 100 times faster than their pur python counterparts and use significantly less memory.

## 4.1 The NumPy ndarray: A Multidimensional Array Object

one of the key featuers of numpy is its n-dimensional array object (ndarray), which is a fast, flexible container for large datasets in python.

In [7]:
data = np.random.randn(2, 3) #generate some random data

In [8]:
data 

array([[-0.82570814, -0.68080259, -0.46071212],
       [-0.90995994, -0.12167156, -0.05096927]])

In [9]:
data * 10

array([[-8.2570814 , -6.8080259 , -4.60712123],
       [-9.0995994 , -1.21671559, -0.50969274]])

In [10]:
data + data

array([[-1.65141628, -1.36160518, -0.92142425],
       [-1.81991988, -0.24334312, -0.10193855]])

an ndarray is a generic multidimensional container for homogeneous data(all elements must be the same type)  
every array has shape and dtype  
.shape produces tuple indicating the size of each dimension  
.dtype produces the data type of the array

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

create array use the array function. accepts any sequence like object (including other arrays) and produces a new numpy array

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])